-- Cloudwerk Auth Migration
-- Generated by: cloudwerk auth migrations
-- Date: 2026-02-03T01:21:32.959Z
--
-- This migration creates the following tables:
--   - user_roles: Required for role-based access control

-- User roles junction table for RBAC
CREATE TABLE IF NOT EXISTS user_roles (
  user_id TEXT NOT NULL,
  role_id TEXT NOT NULL,
  assigned_at TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (user_id, role_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_user_roles_user_id ON user_roles(user_id);
CREATE INDEX IF NOT EXISTS idx_user_roles_role_id ON user_roles(role_id);
