// Auto-generated by cloudwerk bindings - DO NOT EDIT
// Last updated: 2026-01-31T18:21:52.407Z

interface CloudflareBindings {
  // D1 Databases
  DB: D1Database

  // KV Namespaces
  LINKLY_CACHE: KVNamespace
}

// Re-export for convenience
type Env = CloudflareBindings
export type { Env, CloudflareBindings }
