// Auto-generated by cloudwerk bindings - DO NOT EDIT
// Last updated: 2026-01-31T05:26:14.808Z

interface CloudflareBindings {
  // D1 Databases
  DB: D1Database
}

// Re-export for convenience
type Env = CloudflareBindings
export type { Env, CloudflareBindings }
