/**
 * @cloudwerk/cli - Queue Type Generator
 *
 * Generates TypeScript type declarations for queue producers and consumers
 * based on discovered queue definitions in app/queues/.
 */

import * as fs from 'node:fs'
import * as path from 'node:path'
import type { QueueEntry, QueueManifest } from '@cloudwerk/core/build'

// ============================================================================
// Constants
// ============================================================================

const CLOUDWERK_TYPES_DIR = '.cloudwerk/types'
const QUEUES_DTS = 'queues.d.ts'

// ============================================================================
// Types
// ============================================================================

export interface GenerateQueueTypesOptions {
  /** Include timestamp in generated files */
  includeTimestamp?: boolean
}

export interface GenerateQueueTypesResult {
  /** Path to the generated types directory */
  typesDir: string
  /** Path to generated file */
  file: string
  /** Number of queues included */
  queueCount: number
  /** List of queues with their names */
  queues: Array<{ name: string; bindingName: string }>
}

// ============================================================================
// Type Generation
// ============================================================================

/**
 * Generate .cloudwerk/types/queues.d.ts from queue manifest.
 *
 * Creates module declarations for:
 * - @cloudwerk/core/bindings queues proxy with typed queues
 * - @cloudwerk/queue re-exports
 */
export function generateQueueTypes(
  cwd: string,
  manifest: QueueManifest,
  options: GenerateQueueTypesOptions = {}
): GenerateQueueTypesResult {
  const includeTimestamp = options.includeTimestamp ?? true
  const typesDir = path.join(cwd, CLOUDWERK_TYPES_DIR)

  // Ensure directory exists
  fs.mkdirSync(typesDir, { recursive: true })

  // Generate queues.d.ts
  const queuesPath = path.join(typesDir, QUEUES_DTS)
  const queuesContent = generateQueuesDts(manifest.queues, includeTimestamp)
  fs.writeFileSync(queuesPath, queuesContent, 'utf-8')

  // Collect queue info for result
  const queueInfo = manifest.queues.map((q) => ({
    name: q.name,
    bindingName: q.bindingName,
  }))

  return {
    typesDir,
    file: queuesPath,
    queueCount: manifest.queues.length,
    queues: queueInfo,
  }
}

/**
 * Generate queues.d.ts content.
 */
function generateQueuesDts(
  queues: QueueEntry[],
  includeTimestamp: boolean
): string {
  const lines: string[] = []

  // Header
  lines.push('// Auto-generated by cloudwerk queues - DO NOT EDIT')
  if (includeTimestamp) {
    lines.push(`// Last updated: ${new Date().toISOString()}`)
  }
  lines.push('//')
  lines.push('// This file provides type information for queue producers')
  lines.push('// Add ".cloudwerk/types" to your tsconfig.json include array')
  lines.push('')

  // Import Queue type
  lines.push("import type { Queue } from '@cloudwerk/core/bindings'")
  lines.push('')

  // Generate message type placeholders
  // Users should extend these in their own type files
  lines.push('// ============================================================================')
  lines.push('// Message Types')
  lines.push('// ============================================================================')
  lines.push('//')
  lines.push('// Define your message types and update the queue type declarations below.')
  lines.push('// Example:')
  lines.push('//   interface EmailMessage { to: string; subject: string; body: string }')
  lines.push('//')
  lines.push('')

  for (const queue of queues) {
    const typeName = `${capitalizeFirst(queue.name)}Message`
    lines.push(`/** Message type for the '${queue.name}' queue */`)
    lines.push(`// eslint-disable-next-line @typescript-eslint/no-empty-interface`)
    lines.push(`interface ${typeName} {}`)
    lines.push('')
  }

  // Generate queues interface
  lines.push('// ============================================================================')
  lines.push('// Queue Producers Interface')
  lines.push('// ============================================================================')
  lines.push('')
  lines.push('interface CloudwerkQueues {')

  for (const queue of queues) {
    const typeName = `${capitalizeFirst(queue.name)}Message`
    lines.push(`  /** Queue producer for '${queue.name}' (binding: ${queue.bindingName}) */`)
    lines.push(`  ${queue.name}: Queue<${typeName}>`)
  }

  lines.push('}')
  lines.push('')

  // Module declaration for @cloudwerk/core/bindings
  lines.push('// ============================================================================')
  lines.push('// Module Augmentation')
  lines.push('// ============================================================================')
  lines.push('')
  lines.push("declare module '@cloudwerk/core/bindings' {")
  lines.push('  /** Typed queue producers based on app/queues/ definitions */')
  lines.push('  export const queues: CloudwerkQueues')
  lines.push('')
  lines.push('  /** Get a typed queue producer by name */')
  lines.push('  export function getQueue<K extends keyof CloudwerkQueues>(')
  lines.push('    name: K')
  lines.push('  ): CloudwerkQueues[K]')
  lines.push('}')
  lines.push('')

  return lines.join('\n')
}

/**
 * Capitalize the first letter of a string.
 */
function capitalizeFirst(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1)
}

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * Check if .cloudwerk/types/queues.d.ts exists.
 */
export function queueTypesExist(cwd: string): boolean {
  const typesPath = path.join(cwd, CLOUDWERK_TYPES_DIR, QUEUES_DTS)
  return fs.existsSync(typesPath)
}

/**
 * Delete .cloudwerk/types/queues.d.ts if it exists.
 */
export function deleteQueueTypes(cwd: string): boolean {
  const typesPath = path.join(cwd, CLOUDWERK_TYPES_DIR, QUEUES_DTS)
  if (fs.existsSync(typesPath)) {
    fs.unlinkSync(typesPath)
    return true
  }
  return false
}

/**
 * Get path to .cloudwerk/types/queues.d.ts.
 */
export function getQueueTypesPath(cwd: string): string {
  return path.join(cwd, CLOUDWERK_TYPES_DIR, QUEUES_DTS)
}
