/**
 * Client Entry Virtual Module Generator
 *
 * Generates the virtual:cloudwerk/client-entry module that handles
 * client-side hydration of server-rendered components.
 */

import type { RouteManifest } from '@cloudwerk/core/build'
import type { ResolvedCloudwerkOptions, ClientComponentInfo, CssImportInfo } from '../types.js'

/**
 * Collect unique CSS imports from all tracked files.
 */
function collectCssImports(cssImports: Map<string, CssImportInfo[]>): string[] {
  const allCss = new Set<string>()
  for (const imports of cssImports.values()) {
    for (const info of imports) {
      allCss.add(info.absolutePath)
    }
  }
  return Array.from(allCss)
}

/**
 * Generate CSS import statements for the client entry.
 */
function generateCssImportStatements(cssPaths: string[]): string {
  if (cssPaths.length === 0) {
    return ''
  }
  return cssPaths.map((cssPath) => `import '${cssPath}'`).join('\n') + '\n\n'
}

/**
 * Generate the client entry module code.
 *
 * This creates a hydration bootstrap that:
 * - Imports CSS files from layouts and pages
 * - Finds all elements with data-hydrate-id attributes
 * - Dynamically imports the corresponding component bundles
 * - Hydrates each component with its serialized props
 *
 * @param clientComponents - Map of detected client components
 * @param cssImports - Map of CSS imports from layouts and pages
 * @param options - Resolved plugin options
 * @returns Generated JavaScript code
 */
export function generateClientEntry(
  clientComponents: Map<string, ClientComponentInfo>,
  cssImports: Map<string, CssImportInfo[]>,
  options: ResolvedCloudwerkOptions,
  manifest?: RouteManifest
): string {
  const { renderer, hydrationEndpoint, isProduction } = options

  // Collect all unique CSS imports
  const cssPaths = collectCssImports(cssImports)

  if (renderer === 'react') {
    return generateReactClientEntry(clientComponents, cssPaths, hydrationEndpoint, isProduction, manifest)
  }

  return generateHonoClientEntry(clientComponents, cssPaths, hydrationEndpoint, isProduction)
}

/**
 * Configuration for generating production client entries.
 */
interface ProductionEntryConfig {
  /** Header comment for the generated file */
  header: string
  /** CSS import statements */
  cssImports: string
  /** Import statements for the renderer */
  rendererImports: string
  /** Additional declarations (e.g., rootCache for React) */
  additionalDeclarations: string
  /** The hydration call for a single component */
  hydrateCall: string
}

/**
 * Generate static imports and component map for production builds.
 */
function generateStaticImportsAndMap(
  clientComponents: Map<string, ClientComponentInfo>
): { imports: string; componentMapEntries: string } {
  const components = Array.from(clientComponents.values())

  const imports = components.map((info, index) =>
    `import Component${index} from '${info.absolutePath}'`
  ).join('\n')

  const componentMapEntries = components.map((info, index) =>
    `  '${info.componentId}': Component${index}`
  ).join(',\n')

  return { imports, componentMapEntries }
}

/**
 * Generate production client entry with shared structure.
 */
function generateProductionClientEntry(
  clientComponents: Map<string, ClientComponentInfo>,
  config: ProductionEntryConfig
): string {
  const { imports, componentMapEntries } = generateStaticImportsAndMap(clientComponents)

  return `/**
 * ${config.header}
 * This file is auto-generated by @cloudwerk/vite-plugin - do not edit
 */

${config.cssImports}${config.rendererImports}

// Static component imports
${imports}

// Component map for hydration lookups
const components = {
${componentMapEntries}
}
${config.additionalDeclarations}
/**
 * Hydrate all marked elements on the page.
 */
async function hydrate() {
  const elements = document.querySelectorAll('[data-hydrate-id]')
  if (elements.length === 0) {
    console.debug('[Cloudwerk] No client components to hydrate')
    return
  }

  console.debug('[Cloudwerk] Hydrating', elements.length, 'client components')

  for (const el of elements) {
    const componentId = el.getAttribute('data-hydrate-id')
    const propsJson = el.getAttribute('data-hydrate-props')

    if (!componentId) {
      console.warn('[Cloudwerk] Element missing data-hydrate-id')
      continue
    }

    const Component = components[componentId]
    if (!Component) {
      console.warn('[Cloudwerk] Unknown client component:', componentId)
      continue
    }

    try {
      const props = propsJson ? JSON.parse(propsJson) : {}

      ${config.hydrateCall}

      // Clean up hydration attributes
      el.removeAttribute('data-hydrate-id')
      el.removeAttribute('data-hydrate-props')

      console.debug('[Cloudwerk] Hydrated:', componentId)
    } catch (error) {
      console.error('[Cloudwerk] Failed to hydrate component:', componentId, error)
    }
  }
}

// Run hydration when DOM is ready
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', hydrate)
} else {
  hydrate()
}

// Export for manual hydration if needed
export { hydrate }
`
}

/**
 * Generate Hono JSX client entry.
 */
function generateHonoClientEntry(
  clientComponents: Map<string, ClientComponentInfo>,
  cssPaths: string[],
  _hydrationEndpoint: string,
  isProduction: boolean = false
): string {
  const cssImportStatements = generateCssImportStatements(cssPaths)

  // In production, generate static imports and a component map
  // In dev, use dynamic imports with /@fs/ prefix for Vite to serve absolute file paths
  if (isProduction) {
    return generateProductionClientEntry(clientComponents, {
      header: 'Generated Cloudwerk Client Entry (Hono JSX - Production)',
      cssImports: cssImportStatements,
      rendererImports: `import { render } from 'hono/jsx/dom'
import { jsx } from 'hono/jsx/jsx-runtime'`,
      additionalDeclarations: '',
      hydrateCall: `// Hydrate the component using jsx() to create a proper element
      // This allows Hono's reactive system to manage re-renders
      render(jsx(Component, props), el)`,
    })
  }

  const bundleMap = Object.fromEntries(
    Array.from(clientComponents.values()).map((info) => [info.componentId, `/@fs${info.absolutePath}`])
  )

  return `/**
 * Generated Cloudwerk Client Entry (Hono JSX)
 * This file is auto-generated by @cloudwerk/vite-plugin - do not edit
 */

${cssImportStatements}import { render } from 'hono/jsx/dom'
import { jsx } from 'hono/jsx/jsx-runtime'

// Bundle map for component lookups
const bundles = ${JSON.stringify(bundleMap, null, 2)}

// Module cache to avoid re-importing
const moduleCache = new Map()

/**
 * Load a component module, using cache for repeated imports.
 */
async function loadComponent(bundlePath) {
  if (moduleCache.has(bundlePath)) {
    return moduleCache.get(bundlePath)
  }
  const module = await import(/* @vite-ignore */ bundlePath)
  moduleCache.set(bundlePath, module)
  return module
}

/**
 * Hydrate all marked elements on the page.
 */
async function hydrate() {
  const elements = document.querySelectorAll('[data-hydrate-id]')
  if (elements.length === 0) {
    console.debug('[Cloudwerk] No client components to hydrate')
    return
  }

  console.debug('[Cloudwerk] Hydrating', elements.length, 'client components')

  for (const el of elements) {
    const componentId = el.getAttribute('data-hydrate-id')
    const propsJson = el.getAttribute('data-hydrate-props')

    if (!componentId) {
      console.warn('[Cloudwerk] Element missing data-hydrate-id')
      continue
    }

    const bundlePath = bundles[componentId]
    if (!bundlePath) {
      console.warn('[Cloudwerk] Unknown client component:', componentId)
      continue
    }

    try {
      const props = propsJson ? JSON.parse(propsJson) : {}
      const module = await loadComponent(bundlePath)
      const Component = module.default

      if (!Component) {
        console.error('[Cloudwerk] No default export in component:', componentId)
        continue
      }

      // Hydrate the component using jsx() to create a proper element
      // This allows Hono's reactive system to manage re-renders
      render(jsx(Component, props), el)

      // Clean up hydration attributes
      el.removeAttribute('data-hydrate-id')
      el.removeAttribute('data-hydrate-props')

      console.debug('[Cloudwerk] Hydrated:', componentId)
    } catch (error) {
      console.error('[Cloudwerk] Failed to hydrate component:', componentId, error)
    }
  }
}

// Run hydration when DOM is ready
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', hydrate)
} else {
  hydrate()
}

// Export for manual hydration if needed
export { hydrate }
`
}

/**
 * Generate React client entry with full-tree hydration.
 *
 * Instead of island hydration (finding individual data-hydrate-id elements),
 * this reconstructs the full React component tree on the client and hydrates
 * the entire document at once. This enables:
 * - Client components receiving children (e.g., <FadeIn><h1>...</h1></FadeIn>)
 * - React context propagation across component boundaries
 * - No hydration mismatches with motion/framer-motion
 */
function generateReactClientEntry(
  _clientComponents: Map<string, ClientComponentInfo>,
  cssPaths: string[],
  _hydrationEndpoint: string,
  isProduction: boolean = false,
  manifest?: RouteManifest
): string {
  const cssImportStatements = generateCssImportStatements(cssPaths)

  if (!manifest) {
    // Fallback: no manifest available, return minimal entry
    return `/**
 * Generated Cloudwerk Client Entry (React - No Routes)
 * This file is auto-generated by @cloudwerk/vite-plugin - do not edit
 */

${cssImportStatements}console.debug('[Cloudwerk] No route manifest available for React hydration')
`
  }

  // Build imports and route map for all pages and layouts
  const pageImports: string[] = []
  const layoutImports: string[] = []
  const routeMapEntries: string[] = []
  const importedLayouts = new Map<string, string>() // absolutePath -> varName
  let pageIndex = 0
  let layoutIndex = 0

  for (const route of manifest.routes) {
    if (route.fileType !== 'page') continue

    const pageVar = `page_${pageIndex++}`
    const importPath = isProduction ? route.absolutePath : `/@fs${route.absolutePath}`
    pageImports.push(`import * as ${pageVar} from '${importPath}'`)

    // Import layouts for this route
    const layoutVars: string[] = []
    for (const layoutPath of route.layouts) {
      if (!importedLayouts.has(layoutPath)) {
        const layoutVar = `layout_${layoutIndex++}`
        const layoutImportPath = isProduction ? layoutPath : `/@fs${layoutPath}`
        layoutImports.push(`import * as ${layoutVar} from '${layoutImportPath}'`)
        importedLayouts.set(layoutPath, layoutVar)
      }
      layoutVars.push(importedLayouts.get(layoutPath)!)
    }

    routeMapEntries.push(
      `  ${JSON.stringify(route.urlPattern)}: { page: ${pageVar}.default, layouts: [${layoutVars.map(v => `${v}.default`).join(', ')}] }`
    )
  }

  return `/**
 * Generated Cloudwerk Client Entry (React - Full Tree Hydration)
 * This file is auto-generated by @cloudwerk/vite-plugin - do not edit
 */

${cssImportStatements}import { hydrateRoot } from 'react-dom/client'
import { createElement } from 'react'

// Page imports
${pageImports.join('\n')}

// Layout imports
${layoutImports.join('\n')}

// Route map: routeId -> { page, layouts }
const routes = {
${routeMapEntries.join(',\n')}
}

/**
 * Hydrate the full React tree from serialized page data.
 */
function hydrate() {
  const dataEl = document.getElementById('__CLOUDWERK_DATA__')
  if (!dataEl) {
    console.debug('[Cloudwerk] No page data found for React hydration')
    return
  }

  let pageData
  try {
    pageData = JSON.parse(dataEl.textContent || '{}')
  } catch (e) {
    console.error('[Cloudwerk] Failed to parse page data:', e)
    return
  }

  const route = routes[pageData.routeId]
  if (!route) {
    console.error('[Cloudwerk] Unknown route:', pageData.routeId)
    return
  }

  // Reconstruct the component tree (same as server)
  let element = createElement(route.page, pageData.pageProps || {})

  // Wrap with layouts (inside-out, same order as server)
  for (let i = route.layouts.length - 1; i >= 0; i--) {
    const layoutProps = {
      children: element,
      params: pageData.pageProps?.params,
      ...(pageData.layoutData?.[i] || {}),
    }
    element = createElement(route.layouts[i], layoutProps)
  }

  // Hydrate the full tree
  hydrateRoot(document, element)

  console.debug('[Cloudwerk] Full-tree hydration complete for route:', pageData.routeId)
}

// Run hydration when DOM is ready
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', hydrate)
} else {
  hydrate()
}

// Export for manual hydration if needed
export { hydrate }
`
}
