// Auto-generated by cloudwerk bindings - DO NOT EDIT
// Last updated: 2026-02-02T00:19:51.980Z

interface CloudflareBindings {
  // D1 Databases
  DB: D1Database

  // KV Namespaces
  FLAGSHIP_AUTH_SESSIONS: KVNamespace
}

// Re-export for convenience
type Env = CloudflareBindings
export type { Env, CloudflareBindings }
