// Auto-generated by cloudwerk bindings - DO NOT EDIT
// Last updated: 2026-02-01T09:31:51.493Z

interface CloudflareBindings {
  // R2 Buckets
  GALLERY_BUCKET: R2Bucket

  // Images
  IMAGES: import("@cloudwerk/core/bindings").CloudflareImagesBinding

  // Environment Variables
  CF_ACCOUNT_ID: string
  CF_ACCOUNT_HASH: string
}

// Re-export for convenience
type Env = CloudflareBindings
export type { Env, CloudflareBindings }
